"use strict";(self.webpackChunklinkis_web_apache=self.webpackChunklinkis_web_apache||[]).push([[52791],{3905:function(e,n,a){a.d(n,{Zo:function(){return p},kt:function(){return d}});var t=a(67294);function o(e,n,a){return n in e?Object.defineProperty(e,n,{value:a,enumerable:!0,configurable:!0,writable:!0}):e[n]=a,e}function r(e,n){var a=Object.keys(e);if(Object.getOwnPropertySymbols){var t=Object.getOwnPropertySymbols(e);n&&(t=t.filter((function(n){return Object.getOwnPropertyDescriptor(e,n).enumerable}))),a.push.apply(a,t)}return a}function i(e){for(var n=1;n<arguments.length;n++){var a=null!=arguments[n]?arguments[n]:{};n%2?r(Object(a),!0).forEach((function(n){o(e,n,a[n])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(a)):r(Object(a)).forEach((function(n){Object.defineProperty(e,n,Object.getOwnPropertyDescriptor(a,n))}))}return e}function s(e,n){if(null==e)return{};var a,t,o=function(e,n){if(null==e)return{};var a,t,o={},r=Object.keys(e);for(t=0;t<r.length;t++)a=r[t],n.indexOf(a)>=0||(o[a]=e[a]);return o}(e,n);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);for(t=0;t<r.length;t++)a=r[t],n.indexOf(a)>=0||Object.prototype.propertyIsEnumerable.call(e,a)&&(o[a]=e[a])}return o}var l=t.createContext({}),c=function(e){var n=t.useContext(l),a=n;return e&&(a="function"==typeof e?e(n):i(i({},n),e)),a},p=function(e){var n=c(e.components);return t.createElement(l.Provider,{value:n},e.children)},u={inlineCode:"code",wrapper:function(e){var n=e.children;return t.createElement(t.Fragment,{},n)}},h=t.forwardRef((function(e,n){var a=e.components,o=e.mdxType,r=e.originalType,l=e.parentName,p=s(e,["components","mdxType","originalType","parentName"]),h=c(a),d=o,g=h["".concat(l,".").concat(d)]||h[d]||u[d]||r;return a?t.createElement(g,i(i({ref:n},p),{},{components:a})):t.createElement(g,i({ref:n},p))}));function d(e,n){var a=arguments,o=n&&n.mdxType;if("string"==typeof e||o){var r=a.length,i=new Array(r);i[0]=h;var s={};for(var l in n)hasOwnProperty.call(n,l)&&(s[l]=n[l]);s.originalType=e,s.mdxType="string"==typeof e?e:o,i[1]=s;for(var c=2;c<r;c++)i[c]=a[c];return t.createElement.apply(null,i)}return t.createElement.apply(null,a)}h.displayName="MDXCreateElement"},52854:function(e,n,a){a.r(n),a.d(n,{frontMatter:function(){return s},contentTitle:function(){return l},metadata:function(){return c},toc:function(){return p},default:function(){return h}});var t=a(87462),o=a(63366),r=(a(67294),a(3905)),i=["components"],s={},l="Q&A",c={unversionedId:"main",id:"main",title:"Q&A",description:"Linkis1.0 the latest Q&A document//docs.qq.com/doc/DWlN4emlJeEJxWlR0",source:"@site/faq/main.md",sourceDirName:".",slug:"/main",permalink:"/faq/main",editUrl:"https://github.com/apache/incubator-linkis-website/edit/dev/faq/main.md",tags:[],version:"current",frontMatter:{},sidebar:"defaultSidebar"},p=[{value:"Q1, linkis startup error: NoSuchMethodErrorgetSessionManager()Lorg/eclipse/jetty/server/SessionManager",id:"q1-linkis-startup-error-nosuchmethoderrorgetsessionmanagerlorgeclipsejettyserversessionmanager",children:[],level:4},{value:"Q2. When starting the microservice linkis-ps-cs, report DebuggClassWriter overrides final method visit",id:"q2-when-starting-the-microservice-linkis-ps-cs-report-debuggclasswriter-overrides-final-method-visit",children:[],level:4},{value:"Q3. When starting the microservice linkis-ps-datasource, JdbcUtils.getDriverClassName NPE",id:"q3-when-starting-the-microservice-linkis-ps-datasource-jdbcutilsgetdriverclassname-npe",children:[],level:4},{value:"Q4. When starting the microservice linkis-ps-datasource, the following exception ClassNotFoundException HttpClient is reported:",id:"q4-when-starting-the-microservice-linkis-ps-datasource-the-following-exception-classnotfoundexception-httpclient-is-reported",children:[],level:4},{value:"Q5. Click scriptis-database, no data is returned, the phenomenon is as follows:",id:"q5-click-scriptis-database-no-data-is-returned-the-phenomenon-is-as-follows",children:[],level:4},{value:"Q6, shell engine scheduling execution, the page reports Insufficient resource, requesting available engine timeout, eneningeconnmanager linkis.out, and the following error is reported:",id:"q6-shell-engine-scheduling-execution-the-page-reports-insufficient-resource-requesting-available-engine-timeout-eneningeconnmanager-linkisout-and-the-following-error-is-reported",children:[],level:4},{value:"Q7. When the shell engine is scheduled for execution, the engine execution directory reports the following error /bin/java: No such file or directory:",id:"q7-when-the-shell-engine-is-scheduled-for-execution-the-engine-execution-directory-reports-the-following-error-binjava-no-such-file-or-directory",children:[],level:4},{value:"Q8, hive engine scheduling, the following error is reported EngineConnPluginNotFoundException:errorCode:70063",id:"q8-hive-engine-scheduling-the-following-error-is-reported-engineconnpluginnotfoundexceptionerrorcode70063",children:[],level:4},{value:"Q9. After the linkis microservice is started, the following error is reported: Load balancer does not have available server for client:",id:"q9-after-the-linkis-microservice-is-started-the-following-error-is-reported-load-balancer-does-not-have-available-server-for-client",children:[],level:4},{value:"Q10. When the hive engine is scheduled for execution, the following error is reported: operation failed NullPointerException:",id:"q10-when-the-hive-engine-is-scheduled-for-execution-the-following-error-is-reported-operation-failed-nullpointerexception",children:[],level:4},{value:"Q11. When hive engine is scheduled, the error log of engineConnManager is as follows method did not exist: SessionHandler:",id:"q11-when-hive-engine-is-scheduled-the-error-log-of-engineconnmanager-is-as-follows-method-did-not-exist-sessionhandler",children:[],level:4},{value:"After Q12, hive engine restarts, the jar package of jetty 9.4 is always replaced by 9.3",id:"after-q12-hive-engine-restarts-the-jar-package-of-jetty-94-is-always-replaced-by-93",children:[],level:4},{value:"Q13. When the hive engine is executed, the following error is reported: Lcom/google/common/collect/UnmodifiableIterator:",id:"q13-when-the-hive-engine-is-executed-the-following-error-is-reported-lcomgooglecommoncollectunmodifiableiterator",children:[],level:4},{value:"Q14. When the hive engine is executed, the error is reported as follows: TaskExecutionServiceImpl 59 error-org/apache/curator/connection/ConnectionHandlingPolicy:",id:"q14-when-the-hive-engine-is-executed-the-error-is-reported-as-follows-taskexecutionserviceimpl-59-error-orgapachecuratorconnectionconnectionhandlingpolicy",children:[],level:4},{value:"Q15. When the python engine is scheduled, the following error is reported: Python proces is not alive:",id:"q15-when-the-python-engine-is-scheduled-the-following-error-is-reported-python-proces-is-not-alive",children:[],level:4},{value:"Q16. When the spark engine is executed, the following error NoClassDefFoundError: org/apache/hadoop/hive/ql/io/orc/OrcFile is reported:",id:"q16-when-the-spark-engine-is-executed-the-following-error-noclassdeffounderror-orgapachehadoophiveqlioorcorcfile-is-reported",children:[],level:4},{value:"Q17. When the spark engine starts, it reports queue default is not exists in YARN, the specific information is as follows:",id:"q17-when-the-spark-engine-starts-it-reports-queue-default-is-not-exists-in-yarn-the-specific-information-is-as-follows",children:[],level:4},{value:"Q18, when the spark engine starts, an error is reported get the Yarn queue information excepiton. (get the Yarn queue information abnormal) and http link abnormal",id:"q18-when-the-spark-engine-starts-an-error-is-reported-get-the-yarn-queue-information-excepiton-get-the-yarn-queue-information-abnormal-and-http-link-abnormal",children:[],level:4},{value:"Q19. When the spark engine is scheduled, it can be executed successfully for the first time, and if executed again, it will report Spark application sc has already stopped, please restart it. The specific errors are as follows:",id:"q19-when-the-spark-engine-is-scheduled-it-can-be-executed-successfully-for-the-first-time-and-if-executed-again-it-will-report-spark-application-sc-has-already-stopped-please-restart-it-the-specific-errors-are-as-follows",children:[],level:4},{value:"Q20, pythonspark scheduling execution, error: initialize python executor failed ClassNotFoundException org.slf4j.impl.StaticLoggerBinder, as follows:",id:"q20-pythonspark-scheduling-execution-error-initialize-python-executor-failed-classnotfoundexception-orgslf4jimplstaticloggerbinder-as-follows",children:[],level:4},{value:"Q21, pythonspark scheduling execution, error: initialize python executor failed, submit-version error, as follows:",id:"q21-pythonspark-scheduling-execution-error-initialize-python-executor-failed-submit-version-error-as-follows",children:[],level:4},{value:"Q22. When pythonspark is scheduled to execute, it reports TypeError: an integer is required (got type bytes) (executed separately from the command to pull up the engine), the details are as follows:",id:"q22-when-pythonspark-is-scheduled-to-execute-it-reports-typeerror-an-integer-is-required-got-type-bytes-executed-separately-from-the-command-to-pull-up-the-engine-the-details-are-as-follows",children:[],level:4},{value:"Q23, spark engine is 2.4.0+cdh6.3.2, python engine was previously lacking pandas, matplotlib upgraded local python to 3.8, but spark does not support python3.8, only supports below 3.6;",id:"q23-spark-engine-is-240cdh632-python-engine-was-previously-lacking-pandas-matplotlib-upgraded-local-python-to-38-but-spark-does-not-support-python38-only-supports-below-36",children:[],level:4}],u={toc:p};function h(e){var n=e.components,s=(0,o.Z)(e,i);return(0,r.kt)("wrapper",(0,t.Z)({},u,s,{components:n,mdxType:"MDXLayout"}),(0,r.kt)("h1",{id:"qa"},"Q&A"),(0,r.kt)("blockquote",null,(0,r.kt)("p",{parentName:"blockquote"},"Linkis1.0 the latest Q&A document: ",(0,r.kt)("a",{parentName:"p",href:"https://docs.qq.com/doc/DWlN4emlJeEJxWlR0"},"https://docs.qq.com/doc/DWlN4emlJeEJxWlR0"))),(0,r.kt)("h4",{id:"q1-linkis-startup-error-nosuchmethoderrorgetsessionmanagerlorgeclipsejettyserversessionmanager"},"Q1, linkis startup error: NoSuchMethodErrorgetSessionManager()Lorg/eclipse/jetty/server/SessionManager"),(0,r.kt)("p",null,"Specific stack:"),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre"},"Failed startup of context osbwejJettyEmbeddedWebAppContext@6c6919ff{application,/,[file:///tmp/jetty-docbase.9102.6375358926927953589/],UNAVAILABLE} java.lang.NoSuchMethodError: org.eclipse.jetty.server.session.SessionHandler.getSessionManager ()Lorg/eclipse/jetty/server/SessionManager;\nat org.eclipse.jetty.servlet.ServletContextHandler\\$Context.getSessionCookieConfig(ServletContextHandler.java:1415) ~[jetty-servlet-9.3.20.v20170531.jar:9.3.20.v20170531]\n")),(0,r.kt)("p",null,"Solution: jetty-servlet and jetty-security versions need to be upgraded from 9.3.20 to 9.4.20;"),(0,r.kt)("h4",{id:"q2-when-starting-the-microservice-linkis-ps-cs-report-debuggclasswriter-overrides-final-method-visit"},"Q2. When starting the microservice linkis-ps-cs, report DebuggClassWriter overrides final method visit"),(0,r.kt)("p",null,"Specific exception stack: "),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"linkis-exception-01.png",src:a(53018).Z})),(0,r.kt)("p",null,"Solution: jar package conflict, delete asm-5.0.4.jar;"),(0,r.kt)("h4",{id:"q3-when-starting-the-microservice-linkis-ps-datasource-jdbcutilsgetdriverclassname-npe"},"Q3. When starting the microservice linkis-ps-datasource, JdbcUtils.getDriverClassName NPE"),(0,r.kt)("p",null,"Specific exception stack:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"linkis-exception-02.png",src:a(28058).Z})),(0,r.kt)("p",null,"Solution: caused by the Linkis-datasource configuration problem, modify the three parameters at the beginning of linkis.properties hive.meta:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"hive-config-01.png",src:a(47562).Z})),(0,r.kt)("h4",{id:"q4-when-starting-the-microservice-linkis-ps-datasource-the-following-exception-classnotfoundexception-httpclient-is-reported"},"Q4. When starting the microservice linkis-ps-datasource, the following exception ClassNotFoundException HttpClient is reported:"),(0,r.kt)("p",null,"Specific exception stack:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"linkis-exception-03.png",src:a(69153).Z})),(0,r.kt)("p",null,"Solution: There is a problem with linkis-metadata-dev-1.0.0.jar compiled in 1.0, and it needs to be recompiled and packaged."),(0,r.kt)("h4",{id:"q5-click-scriptis-database-no-data-is-returned-the-phenomenon-is-as-follows"},"Q5. Click scriptis-database, no data is returned, the phenomenon is as follows:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"page-show-01.png",src:a(11832).Z})),(0,r.kt)("p",null,"Solution: The reason is that hive is not authorized to Hadoop users. The authorization data is as follows:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"db-config-01.png",src:a(36492).Z})),(0,r.kt)("h4",{id:"q6-shell-engine-scheduling-execution-the-page-reports-insufficient-resource-requesting-available-engine-timeout-eneningeconnmanager-linkisout-and-the-following-error-is-reported"},"Q6, shell engine scheduling execution, the page reports Insufficient resource, requesting available engine timeout, eneningeconnmanager linkis.out, and the following error is reported:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"linkis-exception-04.png",src:a(47895).Z})),(0,r.kt)("p",null,"Solution: The reason Hadoop did not create /appcom/tmp/hadoop/workDir. Create it in advance through the root user, and then authorize the Hadoop user."),(0,r.kt)("h4",{id:"q7-when-the-shell-engine-is-scheduled-for-execution-the-engine-execution-directory-reports-the-following-error-binjava-no-such-file-or-directory"},"Q7. When the shell engine is scheduled for execution, the engine execution directory reports the following error /bin/java: No such file or directory:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"shell-error-01.png",src:a(59204).Z})),(0,r.kt)("p",null,"Solution: There is a problem with the local java environment variables, and you need to make a symbolic link to the java command."),(0,r.kt)("h4",{id:"q8-hive-engine-scheduling-the-following-error-is-reported-engineconnpluginnotfoundexceptionerrorcode70063"},"Q8, hive engine scheduling, the following error is reported EngineConnPluginNotFoundException:errorCode:70063"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"linkis-exception-05.png",src:a(92066).Z})),(0,r.kt)("p",null,"Solution: It is caused by not modifying the version of the corresponding engine during installation, so the engine type inserted into the db by default is the default version, and the compiled version is not caused by the default version. Specific modification steps: cd /appcom/Install/dss-linkis/linkis/lib/linkis-engineconn-plugins/, modify the v2.1.1 directory name in the dist directory to v1.2.1 modify the subdirectory name in the plugin directory 2.1. 1 is 1.2.1 of the default version. If it is Spark, you need to modify dist/v2.4.3 and plugin/2.4.3 accordingly. Finally restart the engineplugin service."),(0,r.kt)("h4",{id:"q9-after-the-linkis-microservice-is-started-the-following-error-is-reported-load-balancer-does-not-have-available-server-for-client"},"Q9. After the linkis microservice is started, the following error is reported: Load balancer does not have available server for client:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"page-show-02.png",src:a(77209).Z})),(0,r.kt)("p",null,"Solution: This is because the linkis microservice has just started and the registration has not been completed. Wait for 1~2 minutes and try again."),(0,r.kt)("h4",{id:"q10-when-the-hive-engine-is-scheduled-for-execution-the-following-error-is-reported-operation-failed-nullpointerexception"},"Q10. When the hive engine is scheduled for execution, the following error is reported: operation failed NullPointerException:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"linkis-exception-06.png",src:a(22634).Z})),(0,r.kt)("p",null,"Solution: The server lacks environment variables, add export HIVE_CONF_DIR=/etc/hive/conf in /etc/profile;"),(0,r.kt)("h4",{id:"q11-when-hive-engine-is-scheduled-the-error-log-of-engineconnmanager-is-as-follows-method-did-not-exist-sessionhandler"},"Q11. When hive engine is scheduled, the error log of engineConnManager is as follows method did not exist: SessionHandler:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"linkis-exception-07.png",src:a(357).Z})),(0,r.kt)("p",null,"Solution: Under the hive engine lib, the jetty jar package conflicts, replace jetty-security and jetty-server with 9.4.20;"),(0,r.kt)("h4",{id:"after-q12-hive-engine-restarts-the-jar-package-of-jetty-94-is-always-replaced-by-93"},"After Q12, hive engine restarts, the jar package of jetty 9.4 is always replaced by 9.3"),(0,r.kt)("p",null,"Solution: When the engine instance is generated, there will be a jar package cache. First, you need to delete the records related to the table linkis_engine_conn_plugin_bml_resources hive, and then delete the records under the directory /appcom/Install/dss-linkis/linkis/lib/linkis-engineconn-plugins/hive/dist 1.2.1.zip, finally restart the engineplugin service, the jar package of lib will be updated successfully."),(0,r.kt)("h4",{id:"q13-when-the-hive-engine-is-executed-the-following-error-is-reported-lcomgooglecommoncollectunmodifiableiterator"},"Q13. When the hive engine is executed, the following error is reported: Lcom/google/common/collect/UnmodifiableIterator:"),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre"},"2021-03-16 13:32:23.304 ERROR [pool-2-thread-1] com.webank.wedatasphere.linkis.engineplugin.hive.executor.HiveEngineConnExecutor 140 run-query failed, reason: java.lang.IllegalAccessError: tried to access method com.google.common.collect.Iterators.emptyIterator() Lcom/google/common/collect/UnmodifiableIterator; from class org.apache.hadoop.hive.ql.exec.FetchOperator\nat org.apache.hadoop.hive.ql.exec.FetchOperator.<init>(FetchOperator.java:108) ~[hive-exec-2.1.1-cdh6.1.0.jar:2.1.1-cdh6.1.0]\nat org.apache.hadoop.hive.ql.exec.FetchTask.initialize(FetchTask.java:86) ~[hive-exec-2.1.1-cdh6.1.0.jar:2.1.1-cdh6.1.0]\nat org.apache.hadoop.hive.ql.Driver.compile(Driver.java:629) ~[hive-exec-2.1.1-cdh6.1.0.jar:2.1.1-cdh6.1.0]\nat org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1414) ~[hive-exec-2.1.1-cdh6.1.0.jar:2.1.1-cdh6.1.0]\nat org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1543) ~[hive-exec-2.1.1-cdh6.1.0.jar:2.1.1-cdh6.1.0]\nat org.apache.hadoop.hive.ql.Driver.run(Driver.java:1332) ~[hive-exec-2.1.1-cdh6.1.0.jar:2.1.1-cdh6.1.0]\nat org.apache.hadoop.hive.ql.Driver.run(Driver.java:1321) ~[hive-exec-2.1.1-cdh6.1.0.jar:2.1.1-cdh6.1.0]\nat com.webank.wedatasphere.linkis.engineplugin.hive.executor.HiveEngineConnExecutor$$anon$1.run(HiveEngineConnExecutor.scala:152) [linkis-engineplugin-hive-dev-1.0.0.jar:?]\nat com.webank.wedatasphere.linkis.engineplugin.hive.executor.HiveEngineConnExecutor$$anon$1.run(HiveEngineConnExecutor.scala:126) [linkis-engineplugin-hive-dev-1.0.0.jar:?]\n")),(0,r.kt)("p",null,"Solution: guava package conflict, kill guava-25.1-jre.jar under hive/dist/v1.2.1/lib;"),(0,r.kt)("h4",{id:"q14-when-the-hive-engine-is-executed-the-error-is-reported-as-follows-taskexecutionserviceimpl-59-error-orgapachecuratorconnectionconnectionhandlingpolicy"},"Q14. When the hive engine is executed, the error is reported as follows: TaskExecutionServiceImpl 59 error-org/apache/curator/connection/ConnectionHandlingPolicy:"),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre"},"2021-03-16 16:17:40.649 INFO [pool-2-thread-1] com.webank.wedatasphere.linkis.engineplugin.hive.executor.HiveEngineConnExecutor 42 info-com.webank.wedatasphere.linkis.engineplugin.hive. executor.HiveEngineConnExecutor@36a7c96f change status Busy => Idle.\n2021-03-16 16:17:40.661 ERROR [pool-2-thread-1] com.webank.wedatasphere.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl 59 error-org/apache/curator/connection/ConnectionHandlingPolicy java .lang.NoClassDefFoundError: org/apache/curator/connection/ConnectionHandlingPolicy at org.apache.curator.framework.CuratorFrameworkFactory.builder(CuratorFrameworkFactory.java:78) ~[curator-framework-4.0.1.jar:4.0.1]\nat org.apache.hadoop.hive.ql.lockmgr.zookeeper.CuratorFrameworkSingleton.getInstance(CuratorFrameworkSingleton.java:59) ~[hive-exec-2.1.1-cdh6.1.0.jar:2.1.1-cdh6.1.0]\nat org.apache.hadoop.hive.ql.lockmgr.zookeeper.ZooKeeperHiveLockManager.setContext(ZooKeeperHiveLockManager.java:98) ~[hive-exec-2.1.1-cdh6.1.0.jar:2.1.1-cdh6.1.0]\nat org.apache.hadoop.hive.ql.lockmgr.DummyTxnManager.getLockManager(DummyTxnManager.java:87) ~[hive-exec-2.1.1-cdh6.1.0.jar:2.1.1-cdh6.1.0]\nat org.apache.hadoop.hive.ql.lockmgr.DummyTxnManager.acquireLocks(DummyTxnManager.java:121) ~[hive-exec-2.1.1-cdh6.1.0.jar:2.1.1-cdh6.1.0]\nat org.apache.hadoop.hive.ql.Driver.acquireLocksAndOpenTxn(Driver.java:1237) ~[hive-exec-2.1.1-cdh6.1.0.jar:2.1.1-cdh6.1.0]\nat org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1607) ~[hive-exec-2.1.1-cdh6.1.0.jar:2.1.1-cdh6.1.0]\nat org.apache.hadoop.hive.ql.Driver.run(Driver.java:1332) ~[hive-exec-2.1.1-cdh6.1.0.jar:2.1.1-cdh6.1.0]\nat org.apache.hadoop.hive.ql.Driver.run(Driver.java:1321) ~[hive-exec-2.1.1-cdh6.1.0.jar:2.1.1-cdh6.1.0]\nat com.webank.wedatasphere.linkis.engineplugin.hive.executor.HiveEngineConnExecutor$$anon$1.run(HiveEngineConnExecutor.scala:152) ~[linkis-engineplugin-hive-dev-1.0.0.jar:?]\nat com.webank.wedatasphere.linkis.engineplugin.hive.executor.HiveEngineConnExecutor$$anon$1.run(HiveEngineConnExecutor.scala:126) ~[linkis-engineplugin-hive-dev-1.0.0.jar:?]\nat java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]\nat javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_181]\nat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1875) ~[hadoop-common-3.0.0-cdh6.3.2.jar:?]\nat com.webank.wedatasphere.linkis.engineplugin.hive.executor.HiveEngineConnExecutor.executeLine(HiveEngineConnExecutor.scala:126) ~[linkis-engineplugin-hive-dev-1.0.0.jar:?]\nat com.webank.wedatasphere.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$execute$1$$anonfun$apply$9$$anonfun$apply$10.apply(ComputationExecutor.scala:145) ~[linkis-computation -engineconn-dev-1.0.0.jar:?]\nat com.webank.wedatasphere.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$execute$1$$anonfun$apply$9$$anonfun$apply$10.apply(ComputationExecutor.scala:144) ~[linkis-computation -engineconn-dev-1.0.0.jar:?]\nat com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) ~[linkis-common-dev-1.0.0.jar:?]\nat com.webank.wedatasphere.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$execute$1$$anonfun$apply$9.apply(ComputationExecutor.scala:146) ~[linkis-computation-engineconn-dev-1.0 .0.jar:?]\nat com.webank.wedatasphere.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$execute$1$$anonfun$apply$9.apply(ComputationExecutor.scala:140) ~[linkis-computation-engineconn-dev-1.0 .0.jar:?]\nat scala.collection.immutable.Range.foreach(Range.scala:160) ~[scala-library-2.11.8.jar:?]\nat com.webank.wedatasphere.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$execute$1.apply(ComputationExecutor.scala:139) ~[linkis-computation-engineconn-dev-1.0.0.jar:? ]\nat com.webank.wedatasphere.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$execute$1.apply(ComputationExecutor.scala:114) ~[linkis-computation-engineconn-dev-1.0.0.jar:? ]\nat com.webank.wedatasphere.linkis.common.utils.Utils$.tryFinally(Utils.scala:62) ~[linkis-common-dev-1.0.0.jar:?]\nat com.webank.wedatasphere.linkis.engineconn.acessible.executor.entity.AccessibleExecutor.ensureIdle(AccessibleExecutor.scala:42) ~[linkis-accessible-executor-dev-1.0.0.jar:?]\nat com.webank.wedatasphere.linkis.engineconn.acessible.executor.entity.AccessibleExecutor.ensureIdle(AccessibleExecutor.scala:36) ~[linkis-accessible-executor-dev-1.0.0.jar:?]\nat com.webank.wedatasphere.linkis.engineconn.computation.executor.execute.ComputationExecutor.ensureOp(ComputationExecutor.scala:103) ~[linkis-computation-engineconn-dev-1.0.0.jar:?]\nat com.webank.wedatasphere.linkis.engineconn.computation.executor.execute.ComputationExecutor.execute(ComputationExecutor.scala:114) ~[linkis-computation-engineconn-dev-1.0.0.jar:?]\nat com.webank.wedatasphere.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anon$1$$anonfun$run$1.apply$mcV$sp(TaskExecutionServiceImpl.scala:139) [linkis-computation-engineconn-dev- 1.0.0.jar:?]\nat com.webank.wedatasphere.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anon$1$$anonfun$run$1.apply(TaskExecutionServiceImpl.scala:138) [linkis-computation-engineconn-dev-1.0.0. jar:?]\nat com.webank.wedatasphere.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anon$1$$anonfun$run$1.apply(TaskExecutionServiceImpl.scala:138) [linkis-computation-engineconn-dev-1.0.0. jar:?]\nat com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) [linkis-common-dev-1.0.0.jar:?]\nat com.webank.wedatasphere.linkis.common.utils.Utils$.tryAndWarn(Utils.scala:74) [linkis-common-dev-1.0.0.jar:?]\nat com.webank.wedatasphere.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anon$1.run(TaskExecutionServiceImpl.scala:138) [linkis-computation-engineconn-dev-1.0.0.jar:?]\nat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]\nat java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]\nat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]\nat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]\nat java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]\nCaused by: java.lang.ClassNotFoundException: org.apache.curator.connection.ConnectionHandlingPolicy atjava.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]\nat java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]\nat sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_181]\nat java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]\n... 39 more\n")),(0,r.kt)("p",null,"Solution: The reason is that there is a corresponding relationship between the version of Curator and the version of zookeeper. For Curator2.X, it supports Zookeeper3.4.X for Curator2.X, so if you are currently Zookeeper3.4.X, you should still use Curator2.X, for example: 2.7.0. Reference link: ",(0,r.kt)("a",{parentName:"p",href:"https://blog.csdn.net/muyingmiao/article/details/100183768"},"https://blog.csdn.net/muyingmiao/article/details/100183768")),(0,r.kt)("h4",{id:"q15-when-the-python-engine-is-scheduled-the-following-error-is-reported-python-proces-is-not-alive"},"Q15. When the python engine is scheduled, the following error is reported: Python proces is not alive:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"linkis-exception-08.png",src:a(67458).Z})),(0,r.kt)("p",null,"Solution: The server installed the anaconda3 package manager. After debugging python, two problems were found: (1) lack of pandas and matplotlib modules, which need to be installed manually; (2) when the new version of the python engine is executed, it depends on the higher version of python, first install python3, Next, make a symbolic link (as shown in the figure below) and restart the engineplugin service."),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"shell-error-02.png",src:a(74611).Z})),(0,r.kt)("h4",{id:"q16-when-the-spark-engine-is-executed-the-following-error-noclassdeffounderror-orgapachehadoophiveqlioorcorcfile-is-reported"},"Q16. When the spark engine is executed, the following error NoClassDefFoundError: org/apache/hadoop/hive/ql/io/orc/OrcFile is reported:"),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre"},"2021-03-19 15:12:49.227 INFO [dag-scheduler-event-loop] org.apache.spark.scheduler.DAGScheduler 57 logInfo -ShuffleMapStage 5 (show at <console>:69) failed in 21.269 s due to Job aborted due to stage failure: Task 1 in stage 5.0 failed 4 times, most recent failure: Lost task 1.3 in stage 5.0 (TID 139, cdh03, executor 6): java.lang.NoClassDefFoundError: org/apache/hadoop/hive/ql /io/orc/OrcFile\nat org.apache.spark.sql.hive.orc.OrcFileOperator$$anonfun$getFileReader$2.apply(OrcFileOperator.scala:75)\nat org.apache.spark.sql.hive.orc.OrcFileOperator$$anonfun$getFileReader$2.apply(OrcFileOperator.scala:73)\nat scala.collection.Iterator$$anon$11.next(Iterator.scala:410)\nat scala.collection.TraversableOnce$class.collectFirst(TraversableOnce.scala:145)\nat scala.collection.AbstractIterator.collectFirst(Iterator.scala:1334)\nat org.apache.spark.sql.hive.orc.OrcFileOperator$.getFileReader(OrcFileOperator.scala:90)\nat org.apache.spark.sql.hive.orc.OrcFileOperator$$anonfun$readSchema$2.apply(OrcFileOperator.scala:99)\nat org.apache.spark.sql.hive.orc.OrcFileOperator$$anonfun$readSchema$2.apply(OrcFileOperator.scala:99)\nat scala.collection.Iterator$$anon$11.next(Iterator.scala:410)\nat scala.collection.TraversableOnce$class.collectFirst(TraversableOnce.scala:145)\nat scala.collection.AbstractIterator.collectFirst(Iterator.scala:1334)\nat org.apache.spark.sql.hive.orc.OrcFileOperator$.readSchema(OrcFileOperator.scala:99)\nat org.apache.spark.sql.hive.orc.OrcFileFormat$$anonfun$buildReader$2.apply(OrcFileFormat.scala:160)\nat org.apache.spark.sql.hive.orc.OrcFileFormat$$anonfun$buildReader$2.apply(OrcFileFormat.scala:151)\nat org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.apply(FileFormat.scala:148)\nat org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.apply(FileFormat.scala:132)\nat org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:126)\nat org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:179)\nat org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:103)\nat org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(UnknownSource)\nat org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)\nat org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$11$$anon$1.hasNext(WholeStageCodegenExec.scala:624)\nat scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)\nat org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)\nat org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)\nat org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)\nat org.apache.spark.scheduler.Task.run(Task.scala:121)\nat org.apache.spark.executor.Executor$TaskRunner$$anonfun$11.apply(Executor.scala:407)\nat org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1408)\nat org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:413)\nat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\nat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\nat java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.ClassNotFoundException: org.apache.hadoop.hive.ql.io.orc.OrcFile\nat java.net.URLClassLoader.findClass(URLClassLoader.java:381)\nat java.lang.ClassLoader.loadClass(ClassLoader.java:424)\nat sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)\nat java.lang.ClassLoader.loadClass(ClassLoader.java:357)\n... 33 more\n\n")),(0,r.kt)("p",null,"Solution: cdh6.3.2 cluster spark engine classpath only has /opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/spark/jars, need to add hive-exec-2.1.1- cdh6.1.0.jar, then restart spark."),(0,r.kt)("h4",{id:"q17-when-the-spark-engine-starts-it-reports-queue-default-is-not-exists-in-yarn-the-specific-information-is-as-follows"},"Q17. When the spark engine starts, it reports queue default is not exists in YARN, the specific information is as follows:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"linkis-exception-09.png",src:a(94241).Z})),(0,r.kt)("p",null,"Solution: When the 1.0 linkis-resource-manager-dev-1.0.0.jar pulls queue information, there is a compatibility problem in parsing json. After the official classmates optimize it, re-provide a new package. The jar package path: /appcom/Install/dss- linkis/linkis/lib/linkis-computation-governance/linkis-cg-linkismanager/."),(0,r.kt)("h4",{id:"q18-when-the-spark-engine-starts-an-error-is-reported-get-the-yarn-queue-information-excepiton-get-the-yarn-queue-information-abnormal-and-http-link-abnormal"},"Q18, when the spark engine starts, an error is reported get the Yarn queue information excepiton. (get the Yarn queue information abnormal) and http link abnormal"),(0,r.kt)("p",null,"Solution: To migrate the address configuration of yarn to the DB configuration, the following configuration needs to be added:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"db-config-02.png",src:a(94801).Z})),(0,r.kt)("h4",{id:"q19-when-the-spark-engine-is-scheduled-it-can-be-executed-successfully-for-the-first-time-and-if-executed-again-it-will-report-spark-application-sc-has-already-stopped-please-restart-it-the-specific-errors-are-as-follows"},"Q19. When the spark engine is scheduled, it can be executed successfully for the first time, and if executed again, it will report Spark application sc has already stopped, please restart it. The specific errors are as follows:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"page-show-03.png",src:a(98842).Z})),(0,r.kt)("p",null,"Solution: The background is that the architecture of the linkis1.0 engine has been adjusted. After the spark session is created, in order to avoid overhead and improve execution efficiency, the session is reused. When we execute spark.scala for the first time, there is spark.stop() in our script. This command will cause the newly created session to be closed. When executed again, it will prompt that the session is closed, please restart it. Solution: first remove stop() from all scripts, and then execute the order: execute default.sql first, then execute scalaspark and pythonspark."),(0,r.kt)("h4",{id:"q20-pythonspark-scheduling-execution-error-initialize-python-executor-failed-classnotfoundexception-orgslf4jimplstaticloggerbinder-as-follows"},"Q20, pythonspark scheduling execution, error: initialize python executor failed ClassNotFoundException org.slf4j.impl.StaticLoggerBinder, as follows:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"linkis-exception-10.png",src:a(37076).Z})),(0,r.kt)("p",null,"Solution: The reason is that the spark server lacks slf4j-log4j12-1.7.25.jar, copy the above jar and report to /opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/spark/jars ."),(0,r.kt)("h4",{id:"q21-pythonspark-scheduling-execution-error-initialize-python-executor-failed-submit-version-error-as-follows"},"Q21, pythonspark scheduling execution, error: initialize python executor failed, submit-version error, as follows:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"shell-error-03.png",src:a(77082).Z})),(0,r.kt)("p",null,"Solution: The reason is that the linkis1.0 pythonSpark engine has a bug in obtaining the spark version code. The fix is \u200b\u200bas follows:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"code-fix-01.png",src:a(63195).Z})),(0,r.kt)("h4",{id:"q22-when-pythonspark-is-scheduled-to-execute-it-reports-typeerror-an-integer-is-required-got-type-bytes-executed-separately-from-the-command-to-pull-up-the-engine-the-details-are-as-follows"},"Q22. When pythonspark is scheduled to execute, it reports TypeError: an integer is required (got type bytes) (executed separately from the command to pull up the engine), the details are as follows:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"shell-error-04.png",src:a(95778).Z})),(0,r.kt)("p",null,"Solution: The reason is that the system spark and python versions are not compatible, python is 3.8, spark is 2.4.0-cdh6.3.2, spark requires python version<=3.6, reduce python to 3.6, comment file /opt/cloudera/parcels/CDH/ The following lines of lib/spark/python/lib/pyspark.zip/pyspark/context.py:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"shell-error-05.png",src:a(41939).Z})),(0,r.kt)("h4",{id:"q23-spark-engine-is-240cdh632-python-engine-was-previously-lacking-pandas-matplotlib-upgraded-local-python-to-38-but-spark-does-not-support-python38-only-supports-below-36"},"Q23, spark engine is 2.4.0+cdh6.3.2, python engine was previously lacking pandas, matplotlib upgraded local python to 3.8, but spark does not support python3.8, only supports below 3.6;"),(0,r.kt)("p",null,"Solution: reinstall the python package manager anaconda2, reduce python to 2.7, install pandas, matplotlib modules, python engine and spark engine can be scheduled normally."))}h.isMDXComponent=!0},63195:function(e,n,a){n.Z=a.p+"assets/images/code-fix-01-d9c67cd0e98241135164e4d6ebb06d1e.png"},36492:function(e,n,a){n.Z=a.p+"assets/images/db-config-01-148b2d1dd324a8082543a67b8a61d031.png"},94801:function(e,n,a){n.Z=a.p+"assets/images/db-config-02-f13268fb7c543733a5c359d9150963fc.png"},47562:function(e,n,a){n.Z=a.p+"assets/images/hive-config-01-38139d9e535f185bee3e17535a5ec327.png"},53018:function(e,n,a){n.Z=a.p+"assets/images/linkis-exception-01-3ce5a64d164882814935b610d226d5d6.png"},28058:function(e,n,a){n.Z=a.p+"assets/images/linkis-exception-02-70fdd83cebfd9f535617f4ada1aa0e66.png"},69153:function(e,n,a){n.Z=a.p+"assets/images/linkis-exception-03-36fb649e7ef97ceeb949ec89a9b8ffb9.png"},47895:function(e,n,a){n.Z=a.p+"assets/images/linkis-exception-04-90263ffdfacbfc69cd63e59955452217.png"},92066:function(e,n,a){n.Z=a.p+"assets/images/linkis-exception-05-79ebb69bb11102bfe287ef83ab4131f9.png"},22634:function(e,n,a){n.Z=a.p+"assets/images/linkis-exception-06-a8da09412508967d9b87712a6e97d74a.png"},357:function(e,n,a){n.Z=a.p+"assets/images/linkis-exception-07-437193907ead2d47135f7761017e8730.png"},67458:function(e,n,a){n.Z=a.p+"assets/images/linkis-exception-08-b615151d4fc8aab21d01bb3bb17ae685.png"},94241:function(e,n,a){n.Z=a.p+"assets/images/linkis-exception-09-015f3ba93f42edda9be668ee5e570a79.png"},37076:function(e,n,a){n.Z=a.p+"assets/images/linkis-exception-10-592b3282c47555a50b0abfe3cafaa6cf.png"},11832:function(e,n,a){n.Z=a.p+"assets/images/page-show-01-cbec3b1161e52e05e9bcdecadd9de3c1.png"},77209:function(e,n,a){n.Z=a.p+"assets/images/page-show-02-f1fe09ca6bd0a2b2d7236e033c51a5de.png"},98842:function(e,n,a){n.Z=a.p+"assets/images/page-show-03-e7a453a712bf9c6b8a580be432de8ab3.png"},59204:function(e,n,a){n.Z=a.p+"assets/images/shell-error-01-170fd7884890c07287d87460366b51c6.png"},74611:function(e,n,a){n.Z=a.p+"assets/images/shell-error-02-7a0828687b976e93aeda516f0d11b8cf.png"},77082:function(e,n,a){n.Z=a.p+"assets/images/shell-error-03-477fba3073827e78efc5a1c3dd76c47a.png"},95778:function(e,n,a){n.Z=a.p+"assets/images/shell-error-04-3a4c1335ed0c7060e3d9ac6bb2aa08c2.png"},41939:function(e,n,a){n.Z=a.p+"assets/images/shell-error-05-44d72941580d17df2297f7a41ef45390.png"}}]);